# Generated by Django 4.2.30 on 2026-07-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('intake_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('sold', 'Sold'), ('reserved', 'Reserved')], default='in_stock', max_length=20)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='inventory.dealership')),
            ],
        ),
        migrations.CreateModel(
            name='AgingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('price_reduction_planned', 'Price Reduction Planned'), ('promotion_planned', 'Promotion Planned'), ('transfer_planned', 'Transfer Planned'), ('no_action', 'No Action')], max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='inventory.vehicle')),
            ],
        ),
    ]
