# Generated by Django 4.2.30 on 2026-07-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='intake_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('sold', 'Sold'), ('reserved', 'Reserved')], db_index=True, default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['dealership', 'status', 'intake_date'], name='inventory_v_dealers_6181fc_idx'),
        ),
    ]
